[package]
name = "rcann-opencl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencl3 = "0.9.1"
rcann = { path = "../rcann" }

[dev-dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
